### PR TITLE
Fix #197 - parse issuer when defined as separate field

### LINKED ISSUE #197: Issuer not properly imported
Hello, 
Thank you for maintaining this app! I found additional small issue :)

I use andOTP and it exports the DB in a strange format

`{"secret":"...,"issuer":"Microsoft","label":"michal@...","digits":6,"type":"TOTP","algorithm":"SHA1","thumbnail":"Microsoft","last_used":123123123,"used_frequency":0,"period":30,"tags":[]}`

But for other keys sometimes it looks like this:

`{"secret":"...,"issuer":"Other Company","label":"Other Company:michal@...","digits":6,"type":"TOTP","algorithm":"SHA1","thumbnail":"Microsoft","last_used":123123123,"used_frequency":0,"period":30,"tags":[]}`

The difference is that in the latter one, there is a label with colon separated issuer and login: `Other Company:michal@...` in addition to issuer field.

It seems that OTPClient reads only the colon separated label, and ignores the issuer field.

I do not know what behaviour is proper here (whether the export of andOTP is inconsistent or OTPClient import does it improperly - unfortunately I do not know that standard).

Anyway I'm letting you know, maybe it's something to fix on your side or maybe on andOTP's :)

I'm OK with closing it as invalid if the problem is on the other side.

### PR DESCRIPTION
**Pull request by michalborek**
I have created a fix to previously created #197 issue. 

I hope it matches the quality, because unfortunately I am not a C developer.

### CODE REVIEW

**Comment by paolostivanin** [comment]
Thanks for the PR! I'll check the logic behind andOTP's code again, and if all is good I'll merge it!

**Comment by michalborek** [comment]
Hi @paolostivanin, I have checked the andOTP code and I will slightly change my implementation to reflect exact behaviour of andOTP. They skip the prefix of label (the text before ":") only if it is the same as issuer. Otherwise they don't skip it and treat as label.

**Comment by michalborek** [comment]
Hi @paolostivanin , I checked the source code of andOTP and I will adjust the logic here to exactly reflect their file format. I'll update this PR today.

**Comment by michalborek** [comment]
The logic behind this is stored here: https://github.com/andOTP/andOTP/blob/e1ced76b5595b94ecabf0756af6ce16ae80cd2b7/app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java#L543

```    
private String getStrippedLabel(String issuer, String label) {
        if (issuer == null || issuer.isEmpty() || !label.startsWith(issuer + ":")) {
            return label.trim();
        } else {
            return label.substring(issuer.length() + 1).trim();
        }
    }
```

So if the label is composite (contains a prefix), then if the prefix it is different than the issuer, the whole string is used as label, otherwise prefix is skipped.

An example entry:
```{"secret":"...","issuer":"Microsoft","label":"My Company:michal@domain.example","digits":6,"type":"TOTP","algorithm":"SHA1","thumbnail":"MyCompany","last_used":1610017199700,"used_frequency":0,"period":30,"tags":[]```

As you can see here, in this case the issuer (Microsoft) is not equal to the prefix in the label, so we should present the full label (My Company:michal@domain.example).

I reflected the same behaviour in the PR.

**Comment by michalborek** [comment]
otpclient

**Comment by michalborek** [comment]
otpclient

**Comment by paolostivanin** [comment]
Thanks a lot, that looks good :)

**Comment by paolostivanin** [comment]
We've gotta check whether the export needs to be updated too before merging the PR :)

**Comment by michalborek** [comment]
Leave it to me :) I'm gonna test the export and reimport

**Comment by paolostivanin** [comment]
Thanks, really appreciated :+1:

**Comment by michalborek** [comment]
I simplified the export logic and it's now based on the andOTP code. Based on their `Entry` class it seems that they simply rewrite the internal state of `issuer` and `label`.

I reflected it in the code by removing the constructed_label and directly writing the label and issue based on the data from DB.

**Comment by paolostivanin** [comment]
Thanks a lot for your help :)
Can you confirm that the following operations work fine?
* [ ] export from andOTP and import the data into OTPClient
  * [ ] at least 1 item in andOTP is without issuer
* [ ] export from OTPClient and import the data into andOTP
  * [ ] at least 1 item in OTPClient is without issuer

**Review by paolostivanin — COMMENTED** [review]
Thanks a lot for your help :)
Can you confirm that the following operations work fine?
* [ ] export from andOTP and import the data into OTPClient
  * [ ] at least 1 item in andOTP must be without issuer
* [ ] export from OTPClient and import the data into andOTP
  * [ ] at least 1 item in OTPClient must be without issuer

**Comment by michalborek** [comment]
I've tested both cases.

When there's no issuer it is simply ignored/empty (the label remains as original e.g. `Test:michal@g....`), so it reflects the behaviour of andOTP.

If the prefix is the same as issuer, then prefix is stripped:

issuer: `Microsoft`, label: `Microsoft:michal@g....` --> issuer: `Microsoft`, label: `michal@g....`

**Comment by paolostivanin** [comment]
Cool, thanks a lot again for your help :)

**Pull request merged**
