### PR TITLE
Edit GtkLabels to improve usability on small screens

### PR DESCRIPTION
**Pull request by pablofsf**
I have a mobile Linux environment and I have been trying to use OTPClient for some time. In most scenarios, it is possible to use a small phone screen. However, there are multiple dialogs which would not fit in the screen and make it complicated to read the text.

This PR aims to fix those dialogs. The idea is to make the dialog fit in smaller screens, while keeping the exact same behavior in regular desktop screens. At the same time, I would like to open the discussion of whether this is something desired in the long-term. I would be very happy to contribute the required code if needed when transitioning to gtk4 or to the new ui that  seems to be under construction :)

This PR still leaves out two dialogs which still don't fit in smaller screens. The reason is that the require some code or ui refactoring that I thought it would be best to leave to once after the discussion above has been addressed:
 * Those dialogs created with `show_message_dialog`, as I haven't found a direct way to make the label wrappable.
 * The "Manually" Add Token dialog, which requires reorganization of some boxes.

### CODE REVIEW

**Comment by paolostivanin** [comment]
Hello, thanks a lot for this PR :)
Just to know whether I have to test it or not, have you tried also on desktop? Does the UI change affects desktop users in any way?
Yes, mobile support would be a nice thing to have. I never looked into it because I don't own a mobile full linux env.
With the port to GTK4 there will be quite some changes (mostly functional due to APIs deprecation/change/etc), but I'm still far from releasing a working beta release because I don't have much free time nowadays :(

**Review by paolostivanin — COMMENTED** [review]
Hello, thanks a lot for this PR :)
Just to know whether I have to test it or not, have you tried also on desktop? Does the UI change affects desktop users in any way?
Yes, mobile support would be a nice thing to have. I never looked into it because I don't own a mobile full linux env.
With the port to GTK4 there will be quite some changes (mostly functional due to APIs deprecation/change/etc), but I'm still far from releasing a working beta release because I don't have much free time nowadays :(

**Comment by pablofsf** [comment]
Yes, I have tried it also on a big display and there isn't any mayor noticeable difference. What happens is that now the dialogs' width is not determined by the amount of text, but by their default width, which changes slightly the appearance. Where I thought it was very noticeable, I added a [default width](https://github.com/paolostivanin/OTPClient/pull/224/files#diff-412db8ae5c17271a2870907a84532da6eed8c36f932e9be6fc561ccf5e05e1dfR1845), so that it  only shrinks the widget in case of missing space. Otherwise newlines might change a bit, but should be decided automatically by gtk.

And great to know that you would be happy to see this happening! I'll try to work on the Manual "Add Token" dialog and post some screenshots if I figure out a way to fit it in small screens without changing the desktop experience much

**Comment by paolostivanin** [comment]
Nice, thanks!
I'm always in favor of supporting more setups, as long as the change doesn't effect (in a negative way) the existing users :)

**Comment by pablofsf** [comment]
Ok, amazing then! I've reworked a bit the Manually Add Token dialog in the last commit. These are some rendered screenshots of the UI change and a picture of the way it looks in my docked pinephone.

Before

otp-before

After

otp-after

Actual picture in a wide screen

otp-desktop

What do you think about this change?

**Comment by paolostivanin** [comment]
Hmm, for mobile it's OK, but for desktop I prefer the current way. But that's just my personal preference.

**Comment by pablofsf** [comment]
Ok, no problem. I've reworked it a bit now to try to keep the original look in large screens. I think there is some slight difference, but I would say it is barely noticeable. Some screenshots:

Before: 
pinephone-before
pinephone-before-large

After:

pinephone-after
pinephone-after-large

**Comment by paolostivanin** [comment]
That's really nice, thanks a lot :)

**Comment by pablofsf** [comment]
Thanks a lot for merging!

As code for the future gtk4 release is still WIP, I would be happy to get involved pushing it forward and help making the UI appealing for both desktop and mobile users. Should I rather look at the `gtk4-switch` or the `new-ui` branch?

**Comment by paolostivanin** [comment]
I suggest you wait until things will get some sort of shape :) currently, the branch `gtk4-switch` is under heavy dev, so you risk working on something for nothing. I'll ping you when the first alpha will become available, so that you can work safely from there.
What do you think?

**Comment by pablofsf** [comment]
That would be great, thank you! A mention in an issue or a MR would send me an email for me to be aware of it :)

**Pull request merged**
